name: Cosign Signer

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  cosign-sign:
    name: Sign a container
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCR_TOKEN }}
          export_default_credentials: true
      - name: setup creds
        run: gcloud auth configure-docker
      - name: Build cosign
        run: go build -o cosign ./cmd/
      # Runs the Super-Linter action
      - name: Cosign sign
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASS: ${{ secrets.COSIGN_PASS }}
        run: |
          cat <<< "$COSIGN_PRIVATE_KEY" > cosign.key;
          echo -n $COSIGN_PASS | ./cosign sign -key cosign.key -a GITHUB_SHA=$GITHUB_SHA -a GITHUB_REPO=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY gcr.io/dlorenc-vmtest2/foo
